---

- hosts: ubuntu.my
  become: yes
  tasks:
  -  name: Install openvpn on Ubuntu
     apt:
        name=openvpn
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:
        openvpn systemd
  handlers:
  - name: openvpn systemd
    systemd:
     name: openvpn.service
     enabled: yes
     state: started
