---

- hosts: ubuntu.my
  become: yes
  tasks:
  -  name: Install nginx on Ubuntu
     apt:
        name=nginx
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:
        nginx systemd
  handlers:
  - name: nginx systemd
    systemd:
     name: nginx.service
     enabled: yes
     state: started
